### ISSUE TITLE
Registering existing commands

### ISSUE THREAD

**Issue by Adaptified** [Pravian/Aero#11]
Currently, I am remapping a plugin with aero and I cannot seem to register a command with the same name as an existing essentials command. Any way to override and register it anyway?

**Comment by JeromSar** [comment]
Yes. Use [this method](https://github.com/Pravian/Aero/blob/master/src/main/java/net/pravian/aero/command/handler/SimpleCommandHandler.java#L156) with force `true`.

**Comment by Adaptified** [comment]
Ok, thanks.
