### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DUFCLiam** [Pravian/Aero#9]
Help:
`import net.pravian.aero.plugin.AeroPlugin;`
does not exits apparently

**Comment by JeromSar** [comment]
It sure does exist: https://github.com/Pravian/Aero/blob/master/src/main/java/net/pravian/aero/plugin/AeroPlugin.java

Are you including Aero in the classpath properly?

**Comment by DUFCLiam** [comment]
@JeromSar I just downloaded Aero (BukkitLib) and added it to the library

**Comment by JeromSar** [comment]
@DUFCLiam BukkitLib is the old version of Aero. There is no compiled version of Aero available yet.

**Comment by DUFCLiam** [comment]
https://github.com/Pravian/Aero/tree/v1.3 ... Compiled?

**Comment by JeromSar** [comment]
You need the new and updated version. :)
